platform :ios, '7.0'

link_with 'Ladio Tail', 'Radio Edge'

pod 'GRMustache', '~> 7.3.0'
pod 'SVProgressHUD', '~> 1.0'
pod 'OpenInChrome', '~> 0.0.1'
pod 'FBNetworkReachability', :git => 'https://github.com/dev5tec/FBNetworkReachability.git'
pod 'ViewDeck', '= 2.2.10'
pod "LINEActivity", :git => 'https://github.com/yhirano/LINEActivity.git', :branch => 'my_pod'
