platform :ios, '7.0'

link_with 'Ladio Tail', 'Radio Edge'

pod 'GRMustache', '~> 7.3.2'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'OpenInChrome', '~> 0.0.1'
pod 'FBNetworkReachability', '~> 1.0.1'
pod 'ViewDeck', '= 2.4.0'
pod "LINEActivity", :git => 'https://github.com/yhirano/LINEActivity.git', :branch => 'my_pod'
pod 'StreamingKit'
pod 'Google-Mobile-Ads-SDK'
pod 'AdMobMediationAdapterIAd'
pod 'NendSDK_iOS'
pod 'NendSDK_iOS_MediationAdapter'

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-acknowledgements.plist', 'LadioTailForIPhone/Settings/LadioTail/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
  FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-acknowledgements.plist', 'LadioTailForIPhone/Settings/RadioEdge/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
